### ISSUE TITLE
Error while importing FirebaseAppProvider

### ISSUE THREAD

**Issue by DavideVito** [FirebaseExtended/reactfire#292] opened 2020-11-21 16:55 UTC
### Version info

**React: 16.3.1**

**Firebase: 8.1.1**

**ReactFire: 2.0.3**

### Steps to reproduce

1) yarn add reactfire firebase
2) import the library using: `import { FirebaseAppProvider } from 'reactfire'`

### Expected behavior

That it works

### Actual behavior

Error: `Attempted import error: 'apps' is not exported from 'firebase/app' (imported as 'firebase').`

**Comment by NSarg7** [comment] 2020-11-21 19:58
Hi everyone.
The problem is here "reactfire/firebaseApp/index.js" line: 19;

import * as firebase from 'firebase/app';   

must be change to 

import firebase from 'firebase/app';

The problem was described [here](https://stackoverflow.com/questions/64545862/upgrade-to-firebase-js-8-0-0-attempted-import-error-app-is-not-exported-from).

**Comment by jamesdaniels** [comment] 2020-11-21 21:37
We're working on new release that supports Firebase v8, in the meantime please stay on Firebase v7.

**Comment by prescottprue** [comment] 2020-11-25 04:21
Great to know @jamesdaniels 

What are thoughts on adding firebase as a peer dependency moving forward. I believe that if we had `"firebase": "^7"` as a peer dependency then it would be clear when installing that you can't use v8 of the firebase sdk with the current version of reactfire

**Comment by coderinblack08** [comment] 2020-11-25 04:47
This is similar to https://github.com/firebase/firebaseui-web/issues/771. I tired manually editing the node_modules to change the imports. No luck. Any quick fixes?

**Comment by coderinblack08** [comment] 2020-11-25 04:50
I ran `yarn add firebase@^7.0.0`, but I'm still getting the error...

**Comment by jamesdaniels** [comment] 2020-12-10 00:21
Closing as we support v8 with 3.0.0-rc.0 and master & have started including a peerDep in the package.json

**Closed by jamesdaniels** 2020-12-10 00:21 UTC
