### ISSUE TITLE
[QUESTION] Is there a way to alter limitToLast value? 

### ISSUE THREAD

**Issue by MuratDoner** [FirebaseExtended/reactfire#168] opened 2019-10-23 14:54 UTC
Hello,
   I try to create a simple pagination based on scrolling. When scroll touches the top, **contentCount** increases.
  So, we alter limit actually but it does not effect the result.

   ```
const [contentCount, setContentCount] = useState(9)
   const firebaseApp = useFirebaseApp();
    const ref  firebaseApp.database().ref('dialogContents').orderByKey().limitToLast(contentCount);
```

What is the best way to change this limit?

Best regards

**Comment by jhuleatt** [comment] 2019-10-23 18:45
Hey @MuratDoner , this is caused by a bug in ReactFire where it failed to requery if `limitToLast` or other query modifiers were changed. It will be fixed by #167

**Comment by MuratDoner** [comment] 2019-10-23 19:42
Thank you @jhuleatt.
Then we can just close this issue and follow on the related issue.

**Comment by MuratDoner** [comment] 2019-10-29 15:02
@jhuleatt Hello.
 Even when I use `firebaseApp.firestore().collection(collectionName)` from different hooks, components changing **collectionName** for each; result does not change sometimes.
 Is it also related to that issue?

**Comment by jhuleatt** [comment] 2019-10-31 21:56
Hey @MuratDoner can you please give the latest build of ReactFire a try and see if you can reproduce the issue? I think #167 should fix that too.

If that doesn't fix it and you have the time, can you please send a CodeSandbox/StackBlitz link that reproduces it?

**Comment by MuratDoner** [comment] 2019-11-01 09:40
Hey @jhuleatt,

I add the latest version, but got an error like this:
 
Attempted import error: '**useFirestoreCollectionData**' is not exported from '**reactfire**'.

Should I do something else?

**Comment by jhuleatt** [comment] 2019-11-01 19:55
Sounds like an old version is being pulled in. Can you please try `yarn add reactfire@canary` or `npm install reactfire@canary` in your project?

**Comment by MuratDoner** [comment] 2019-11-02 15:21
Hey @jhuleatt,
It works like a charm now :)
Sample:
https://codesandbox.io/embed/elated-dijkstra-7u6i7?fontsize=14

**Comment by jhuleatt** [comment] 2019-11-04 20:54
Great!

**Closed by jhuleatt** 2019-11-04 20:54 UTC
